# Generated by Django 3.1.3 on 2020-11-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(default='', max_length=30)),
                ('x_coordinate', models.IntegerField(default=0)),
                ('y_coordinate', models.IntegerField(default=0)),
            ],
        ),
    ]
